inferenceNetwork <- function(expressionData, writeData = FALSE, pathOut = "."){
  # -- gera matriz transposta
  expressionDataTransposto <- t(expressionData)
  colnames(expressionDataTransposto) <- rep(1:length(row.names(expressionData)))
  #--- discretizar para métodos MI  # default do infotheo função discretize()
  cat("Executing unsupervised data discretization...\n")
  expressionTranspDiscret <- infotheo::discretize(expressionDataTransposto)
  cat("Executing NetBc3...\n")
  netBc3 <- runBc3Net(expressionDataTransposto,writeData, pathOut)
  cat("Executing NetC3...\n")
  netC3 <- runC3net(expressionTranspDiscret, writeData, pathOut)
  cat("Executing ARACNE...\n")
  netAracne <- runAracne(expressionTranspDiscret, writeData, pathOut)
  cat("Executing CLR...\n")
  netClr <- runClr(expressionTranspDiscret, writeData, pathOut)
  cat("Executing MRNet...\n")
  netMrnet <- runMRnet(expressionTranspDiscret, writeData, pathOut)
  cat("Executing MRNetB...\n")
  netMrnetB <- runMrnetB(expressionTranspDiscret, writeData, pathOut)
  cat("Executing MRNetB...\n")
  netGENIE3 <- runGENIE3(expressionTranspDiscret, writeData, pathOut)
  networks <- list(netBc3, netC3, netAracne, netClr, netMrnet, netMrnetB, netGENIE3)
  names(networks) <- c("BC3", "C3NET", "ARACNE", "CLR", "mrnet", "mrnetB", "GENIE3")
  
  if(writeData){
    cat("Writting data...\n")
    # fileName <- paste0(pathOut,"listAllNetworks_predicted.csv")
    # writeNetworkCsv(networks, fileName)
    fileR = paste0(pathOut,"listAllNetworks_predicted_predicted.RData")
    writeRData(networks, fileR)
    remove(fileR)
  }
  remove(netBc3, netC3, netAracne, netClr, netMrnet, netMrnetB)
  return(networks)
}