inferenceNetwork <- function(expressionData, writeData = FALSE, pathOut = "."){
  #--- discretizar para métodos MI  # default do infotheo função discretize()
  # message("Executing unsupervised data discretization...")
  # expressionData <- infotheo::discretize(expressionData)
  message("Executing NetBc3...")
  netBc3 <- runBc3Net(as.matrix(expressionData),writeData, pathOut)
  message("Executing NetC3...")
  netC3 <- runC3net(as.matrix(expressionData), writeData, pathOut)
  message("Executing ARACNE...")
  netAracne <- runAracne(expressionData, writeData, pathOut)
  message("Executing CLR...")
  netClr <- runClr(expressionData, writeData, pathOut)
  message("Executing MRNet...")
  netMrnet <- runMRnet(expressionData, writeData, pathOut)
  message("Executing MRNetB...")
  netMrnetB <- runMrnetB(expressionData, writeData, pathOut)
  networks <- list(netBc3, netC3, netAracne, netClr, netMrnet, netMrnetB)
  names(networks) <- c("netBc3", "netC3", "netAracne", "netClr", "netMrnet", "netMrnetB")
  
  if(writeData){
    message("Writting data...")
    # fileName <- paste0(pathOut,"listAllNetworks_predicted.csv")
    # writeNetworkCsv(networks, fileName)
    fileR = paste0(pathOut,"listAllNetworks_predicted_predicted.RData")
    writeRData(networks, fileR)
    remove(fileR)
  }
  remove(netBc3, netC3, netAracne, netClr, netMrnet, netMrnetB)
  return(networks)
}